<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Jotunn</AssemblyName>
    <RootNamespace>Jotunn</RootNamespace>
    <Version>2.30.1</Version>
    <AssemblyVersion>2.30.1.0</AssemblyVersion>
    <FileVersion>2.30.1.0</FileVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <ValheimManaged>$(ValheimInstall)\Valheim_Data\Managed</ValheimManaged>
    <BepInExCore>$(ValheimInstall)\BepInEx\core</BepInExCore>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCore)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCore)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(BepInExCore)\Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="$(ValheimManaged)\publicized_assemblies\*.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(ValheimManaged)\UnityEngine*.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(ValheimManaged)\Unity.TextMeshPro.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(ValheimManaged)\PlayFab.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(ValheimManaged)\PlayFabParty.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(ValheimManaged)\Splatform.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
