<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Jotunn</AssemblyName>
    <RootNamespace>Jotunn</RootNamespace>
    <Version>2.30.1</Version>
    <AssemblyVersion>2.30.1.0</AssemblyVersion>
    <FileVersion>2.30.1.0</FileVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <SlimLibDir>$(MSBuildThisFileDirectory)..\..\lib</SlimLibDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference
      Include="CoffeeNova.Valheim.ManagedReferences"
      Version="1.2214.6"
      PrivateAssets="all"
      Condition="'$(ValheimManaged)' == ''" />
  </ItemGroup>

  <ItemGroup Condition="'$(ValheimManaged)' != ''">
    <Reference Include="BepInEx">
      <HintPath>$(SlimLibDir)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(SlimLibDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <_ValheimManagedReference Include="$(ValheimManaged)\Assembly-CSharp.dll" />
    <_ValheimManagedReference Include="$(ValheimManaged)\assembly_valheim.dll"
                              Condition="Exists('$(ValheimManaged)\assembly_valheim.dll')" />
    <_ValheimManagedReference Include="$(ValheimManaged)\assembly_utils.dll"
                              Condition="Exists('$(ValheimManaged)\assembly_utils.dll')" />
    <_ValheimManagedReference Include="$(ValheimManaged)\assembly_guiutils.dll"
                              Condition="Exists('$(ValheimManaged)\assembly_guiutils.dll')" />
    <_ValheimManagedReference Include="$(ValheimManaged)\SoftReferenceableAssets.dll" />
    <_ValheimManagedReference Include="$(ValheimManaged)\UnityEngine*.dll"
                              Exclude="$(ValheimManaged)\UnityEngine.ImageConversionModule.dll" />

    <Reference Include="@(_ValheimManagedReference)">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
