<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>ServerTorchRefill</AssemblyName>
    <RootNamespace>ServerTorchRefillMod</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>lib\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ServersideQoL">
      <HintPath>lib\ServersideQoL.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="YamlDotNet">
      <HintPath>lib\YamlDotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>lib\assembly_valheim.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>lib\assembly_utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>lib\assembly_guiutils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SoftReferenceableAssets">
      <HintPath>lib\SoftReferenceableAssets.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>lib\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>lib\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>lib\Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>lib\MonoMod.Utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
