(()=>{'use strict';
if(window.__tagGremlinV8){window.__tagGremlinV8.show();return}
const H=location.hostname,DBN='tag-gremlin-v8:'+H,OLD='tag-gremlin-v7:'+H,K=40,BATCH=20,
ROOT=[...'abcdefghijklmnopqrstuvwxyz0123456789'],NEXT=[...'abcdefghijklmnopqrstuvwxyz0123456789.-'],V=/^[a-z0-9][a-z0-9.-]*$/,
MAX_SUB=4,MAX_PRE=64;
let P,st,ct,px,wk,lg,I,db,wake=null,running=0,paused=0,pending=0,frontier=new Set(),tags=new Map(),grams=new Map(),closedByLen=new Map(),dirtyTags=new Map(),dirtyGrams=new Map(),hist=[],subC=new Map(),subW=new Map(),preC=new Map(),preW=new Map(),parentStats=new Map(),session=null;
let S={v:8,requests:0,processed:0,inferred:0,covered:0,importedTags:0,importedProofs:0,turn:0,yieldEwma:8,latEwma:0,done:0,ep:null};
const sleep=n=>new Promise(r=>setTimeout(r,n)),vis=e=>{if(!e||!e.getBoundingClientRect)return 0;let r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!='none'&&s.visibility!='hidden'},req=r=>new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)}),txdone=t=>new Promise((ok,no)=>{t.oncomplete=ok;t.onerror=()=>no(t.error);t.onabort=()=>no(t.error)}),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const openDB=()=>new Promise((ok,no)=>{let r=indexedDB.open(DBN,1);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains('tags'))d.createObjectStore('tags',{keyPath:'name'});if(!d.objectStoreNames.contains('grams'))d.createObjectStore('grams',{keyPath:'q'});if(!d.objectStoreNames.contains('meta'))d.createObjectStore('meta')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)}),all=(d,s)=>req(d.transaction(s,'readonly').objectStore(s).getAll()),meta=d=>req(d.transaction('meta','readonly').objectStore('meta').get('state'));
const closeAdd=q=>{let n=q.length,s=closedByLen.get(n);if(!s)closedByLen.set(n,s=new Set);s.add(q)},coverOf=q=>{let best='';for(const [n,s] of closedByLen){if(n>q.length)continue;for(let i=0;i<=q.length-n;i++){let x=q.slice(i,i+n);if(s.has(x)&&(!best||x.length<best.length))best=x}}return best},isCovered=q=>!!coverOf(q);
const wtag=c=>1+Math.min(3,0.6*Math.log10(1+Math.max(0,c||0))),bump=(m,k,v=1)=>m.set(k,(m.get(k)||0)+v);
const indexTag=(n,c)=>{let w=wtag(c),seen=new Set;for(let L=1;L<=Math.min(MAX_SUB,n.length);L++)for(let i=0;i<=n.length-L;i++)seen.add(n.slice(i,i+L));for(const q of seen){bump(subC,q,1);bump(subW,q,w)}for(let L=1;L<=Math.min(MAX_PRE,n.length);L++){let q=n.slice(0,L);bump(preC,q,1);bump(preW,q,w)}};
const rebuildIndexes=()=>{subC=new Map;subW=new Map;preC=new Map;preW=new Map;for(const [n,c] of tags)indexTag(n,c)};
const addTag=(n,c)=>{n=String(n||'').trim().toLowerCase();if(!V.test(n))return 0;let had=tags.has(n),old=tags.get(n)||0,nv=Math.max(old,Number.isFinite(+c)?+c:0);if(!had){tags.set(n,nv);dirtyTags.set(n,nv);indexTag(n,nv);return 1}if(nv>old){tags.set(n,nv);dirtyTags.set(n,nv)}return 0};
const addGram=(q,count,kind,newTags=0)=>{let rec={q,count,kind,newTags};grams.set(q,rec);dirtyGrams.set(q,rec);if(count<K)closeAdd(q);if(q.length>1){let p=q.slice(0,-1),a=parentStats.get(p)||{n:0,y:0,s:0,c:0};a.n++;a.y+=newTags;if(count>=K)a.s++;else a.c++;parentStats.set(p,a)}};
const importV7=async()=>{let od=null;try{od=await new Promise((ok,no)=>{let r=indexedDB.open(OLD);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});if(!od.objectStoreNames.contains('tags')||!od.objectStoreNames.contains('grams')){od.close();return false}let [ta,ga,me]=await Promise.all([all(od,'tags'),all(od,'grams'),od.objectStoreNames.contains('meta')?meta(od):Promise.resolve(null)]);for(const x of ta)addTag(x.name,x.count||0);for(const x of ga){let count=+x.count||0,kind=count<K?'closed':'imported-saturated';addGram(String(x.q),count,kind,0)}if(me&&me.ep)S.ep=me.ep;S.importedTags=ta.length;S.importedProofs=ga.length;od.close();return !!(ta.length||ga.length)}catch{try{od&&od.close()}catch{}return false}};
const buildParentStats=()=>{parentStats=new Map;for(const r of grams.values())if(r.q&&r.q.length>1){let p=r.q.slice(0,-1),a=parentStats.get(p)||{n:0,y:0,s:0,c:0};a.n++;a.y+=r.newTags||0;if(r.count>=K)a.s++;else a.c++;parentStats.set(p,a)}};
const rebuildFrontier=()=>{frontier=new Set;for(const r of ROOT)if(!grams.has(r)&&!isCovered(r))frontier.add(r);for(const [q,g] of grams){if(g.count<K||isCovered(q))continue;for(const c of NEXT){let x=q+c;if(!grams.has(x)&&!isCovered(x))frontier.add(x)}}pruneFrontier()};
const pruneFrontier=()=>{let n=0;for(const q of [...frontier])if(isCovered(q)){frontier.delete(q);n++}if(n)S.covered+=n;return n};
const load=async()=>{db=await openDB();let [ta,ga,me]=await Promise.all([all(db,'tags'),all(db,'grams'),meta(db)]);if(me&&me.v===8){for(const x of ta)tags.set(x.name,x.count||0);for(const x of ga){let r={q:String(x.q),count:+x.count||0,kind:x.kind||((+x.count||0)<K?'closed':'saturated'),newTags:+x.newTags||0};grams.set(r.q,r);if(r.count<K)closeAdd(r.q)}S={...S,...me};rebuildIndexes();buildParentStats()}else{await importV7();rebuildIndexes();buildParentStats();await flush()}rebuildFrontier();if(!frontier.size)S.done=1};
const flush=async()=>{if(!db)return;let t=db.transaction(['tags','grams','meta'],'readwrite'),ts=t.objectStore('tags'),gs=t.objectStore('grams'),ms=t.objectStore('meta');for(const [name,count] of dirtyTags)ts.put({name,count});for(const [q,r] of dirtyGrams)gs.put(r);ms.put({...S},'state');dirtyTags.clear();dirtyGrams.clear();pending=0;await txdone(t)};
const find=()=>{for(const l of document.querySelectorAll('label'))if(/^\s*tags?\s*:?\s*$/i.test(l.textContent||'')){let x=l.htmlFor&&document.getElementById(l.htmlFor)||l.querySelector('input,textarea');if(x)return x}let a=[...document.querySelectorAll('input:not([type]),input[type=text],input[type=search],textarea')].filter(vis),f=document.activeElement;return f&&/^(INPUT|TEXTAREA)$/.test(f.tagName)?f:a[a.length-1]};
const setval=v=>{let p=I.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,s=Object.getOwnPropertyDescriptor(p,'value')?.set;s?s.call(I,v):I.value=v},fire=(t,k)=>{try{I.dispatchEvent(new KeyboardEvent(t,{key:k,code:/^[a-z]$/i.test(k)?'Key'+k.toUpperCase():/^[0-9]$/.test(k)?'Digit'+k:'',keyCode:k.charCodeAt(0),which:k.charCodeAt(0),bubbles:true,cancelable:true}))}catch{}},jq=(t,k)=>{try{if(window.jQuery){let e=jQuery.Event(t);e.key=k;e.which=e.keyCode=k?k.charCodeAt(0):0;jQuery(I).trigger(e)}}catch{}},typeq=async q=>{I.focus();setval('');try{I.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'deleteContentBackward',data:null}))}catch{I.dispatchEvent(new Event('input',{bubbles:true}))}jq('input','');await sleep(70);let v='';for(const ch of q){fire('keydown',ch);jq('keydown',ch);fire('keypress',ch);jq('keypress',ch);v+=ch;setval(v);try{I.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:ch}))}catch{I.dispatchEvent(new Event('input',{bubbles:true}))}jq('input',ch);fire('keyup',ch);jq('keyup',ch);await sleep(100)}I.dispatchEvent(new Event('change',{bubbles:true}));jq('change',q.slice(-1))};
const rows=()=>{let ir=I.getBoundingClientRect(),m=new Map,re=/^\s*(.+?)\s*\(([\d,]+)\)\s*$/;for(const e of document.querySelectorAll('li,a,div,span,td')){if(!vis(e))continue;let r=e.getBoundingClientRect();if(r.bottom<ir.top-60||r.top>ir.bottom+1100)continue;let t=(e.textContent||'').replace(/\s+/g,' ').trim(),z=t.match(re);if(!z)continue;let n=z[1].trim().toLowerCase(),c=+z[2].replace(/,/g,'');if(V.test(n)&&Number.isFinite(c)&&!m.has(n))m.set(n,c)}return[...m].map(([name,count])=>({name,count}))},waitRows=async()=>{let b=[];for(let i=0;i<12;i++){await sleep(i?160:220);let a=rows();if(a.length)b=a;if(a.length&&i>=2)return a}return b};
const walk=(x,f,p=[])=>{f(x,p);if(Array.isArray(x))x.forEach((v,i)=>walk(v,f,p.concat(i)));else if(x&&typeof x==='object')for(const k of Object.keys(x))walk(x[k],f,p.concat(k))},at=(x,p)=>{for(const k of p){if(x==null)return undefined;x=x[k]}return x},arrInfo=(j,known)=>{let b=null;walk(j,(v,p)=>{if(!Array.isArray(v)||!v.length)return;let h=0;for(const it of v){let hit=0;walk(it,w=>{if(typeof w==='string'&&known.has(w.toLowerCase()))hit=1});h+=hit}if(h&&(!b||h>b.h||(h===b.h&&v.length<b.n)))b={p,h,n:v.length}});return b},namePath=(a,known)=>{let m=new Map;for(const it of a)walk(it,(v,p)=>{if(typeof v==='string'&&known.has(v.toLowerCase())){let k=JSON.stringify(p);m.set(k,(m.get(k)||0)+1)}});let b=[...m].sort((x,y)=>y[1]-x[1])[0];return b?JSON.parse(b[0]):null},countPath=(a,np,vm)=>{let m=new Map;for(const it of a){let n=at(it,np);if(typeof n!=='string')continue;let want=vm.get(n.toLowerCase());if(want==null)continue;walk(it,(v,p)=>{if((typeof v==='number'||(typeof v==='string'&&/^\d+$/.test(v)))&&+v===want){let k=JSON.stringify(p);m.set(k,(m.get(k)||0)+1)}})}let b=[...m].sort((x,y)=>y[1]-x[1])[0];return b&&b[1]>=2?JSON.parse(b[0]):null},decode=s=>{try{return decodeURIComponent(String(s||'').replace(/\+/g,' ')).toLowerCase()}catch{return String(s||'').toLowerCase()}},qKey=(u,q)=>{try{let U=new URL(u),soft=[];for(const [k,v] of U.searchParams){let d=decode(v);if(d===q.toLowerCase())return k;if(d.includes(q.toLowerCase()))soft.push(k)}return soft[0]||null}catch{return null}},parse=(j,ep)=>{let a=at(j,ep.arr);if(!Array.isArray(a))throw Error('result-array-missing');let out=[];for(const it of a){let n=at(it,ep.name);if(typeof n!=='string')continue;n=n.toLowerCase().trim();if(!V.test(n))continue;let c=ep.count?+at(it,ep.count):0;if(!Number.isFinite(c))c=0;out.push({name:n,count:c})}return{raw:a.length,tags:out}};
const discover=async q=>{I=find();if(!I)throw Error('tap-tags-field-first');const xp=XMLHttpRequest.prototype,op=xp.open,os=xp.send,R=[];xp.open=function(m,u){try{this.__tg8={m:String(m||'GET').toUpperCase(),u:new URL(u,location.href).href}}catch{}return op.apply(this,arguments)};xp.send=function(){let d=this.__tg8;if(d&&d.m==='GET'){let r={u:d.u,st:0,ct:'',t:''};R.push(r);this.addEventListener('loadend',()=>{r.st=this.status;try{r.ct=this.getResponseHeader('content-type')||''}catch{}try{if(!this.responseType||this.responseType==='text')r.t=String(this.responseText||'')}catch{}},{once:true})}return os.apply(this,arguments)};try{let t0=performance.now();S.requests++;await typeq(q);let vr=await waitRows(),vm=new Map(vr.map(x=>[x.name,x.count]));await sleep(400);let cand=R.filter(r=>r.st===200&&/json/i.test(r.ct)&&decode(r.u).includes(q.toLowerCase())).map(r=>{let h=0,l=r.t.toLowerCase();for(const x of vr)if(l.includes(x.name))h++;return{r,h}}).sort((a,b)=>b.h-a.h||b.r.t.length-a.r.t.length)[0];if(!cand||!cand.h)throw Error('endpoint-not-found');let key=qKey(cand.r.u,q);if(!key)throw Error('query-key-not-found');let j=JSON.parse(cand.r.t),known=new Set(vr.map(x=>x.name)),ai=arrInfo(j,known);if(!ai)throw Error('result-array-not-found');let a=at(j,ai.p),np=namePath(a,known);if(!np)throw Error('tag-field-not-found');let cp=countPath(a,np,vm);S.ep={url:cand.r.u,key,arr:ai.p,name:np,count:cp};updateLatency(performance.now()-t0);return parse(j,S.ep)}finally{xp.open=op;xp.send=os}};
const direct=async q=>{let U=new URL(S.ep.url);U.searchParams.set(S.ep.key,q);let t0=performance.now();S.requests++;let r=await fetch(U.href,{credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}});if(!r.ok)throw Error('endpoint-http-'+r.status);let j=await r.json(),x=parse(j,S.ep);updateLatency(performance.now()-t0);if(x.tags.length&&x.tags.filter(t=>t.name.includes(q)).length<x.tags.length*.8)throw Error('endpoint-query-mismatch');return x},updateLatency=ms=>S.latEwma=S.latEwma?S.latEwma*.82+ms*.18:ms;
const knownContain=q=>q.length<=MAX_SUB?(subC.get(q)||0):0,knownContainAtLeast=(q,n)=>{if(q.length<=MAX_SUB)return(subC.get(q)||0)>=n;let c=0;for(const t of tags.keys())if(t.includes(q)&&++c>=n)return true;return false},knownPrefix=q=>preC.get(q)||0,weightedContain=q=>q.length<=MAX_SUB?(subW.get(q)||0):0,weightedPrefix=q=>preW.get(q)||0;
const lmScore=q=>{let d=weightedContain(q),p=weightedPrefix(q),s2=q.length>=2?(subW.get(q.slice(-2))||0):0,s3=q.length>=3?(subW.get(q.slice(-3))||0):0,h2=q.length>=2?(preW.get(q.slice(0,2))||0):0,h3=q.length>=3?(preW.get(q.slice(0,3))||0):0;return 2.8*Math.log1p(p)+1.5*Math.log1p(d)+.65*Math.log1p(s3)+.3*Math.log1p(s2)+.5*Math.log1p(h3)+.25*Math.log1p(h2)};
const feat=q=>{let d=knownContain(q),p=knownPrefix(q),lm=lmScore(q),ps=parentStats.get(q.slice(0,-1)),sibY=ps&&ps.n?ps.y/ps.n:0,sibSat=ps&&ps.n?ps.s/ps.n:.5,sibClose=ps&&ps.n?ps.c/ps.n:.5,nov=1-Math.min(K,d)/K,depth=q.length;return{d,p,lm,sibY,sibSat,sibClose,nov,depth}};
const harvestScore=q=>{let f=feat(q);return (9*f.lm+2.2*f.sibY+11*f.sibSat+3*Math.log1p(f.p))*(.45+.55*f.nov)-1.25*(f.depth-1)},pruneScore=q=>{let f=feat(q);return 1.25*(K-Math.min(K,f.d))+22*f.sibClose+22/f.depth-3.5*f.lm-5*f.sibSat};
const modePlan=()=>{let y=S.yieldEwma||0;if(y>=8)return{h:4,p:1};if(y>=4)return{h:3,p:1};if(y>=1.5)return{h:2,p:1};return{h:1,p:2}},chooseMode=()=>{let x=modePlan(),n=x.h+x.p,m=S.turn%n;return m<x.h?'harvest':'prune'},depthRange=()=>{let mn=99,mx=0;for(const q of frontier){if(isCovered(q))continue;mn=Math.min(mn,q.length);mx=Math.max(mx,q.length)}return[mn===99?0:mn,mx]},choose=mode=>{let [mn]=depthRange();if(!mn)return null;let horizon=mode==='prune'?mn+1:mn+(S.yieldEwma>=6?3:S.yieldEwma>=2?2:1),best=null,bs=-Infinity;for(const q of frontier){if(q.length>horizon||isCovered(q))continue;let s=mode==='harvest'?harvestScore(q):pruneScore(q);if(s>bs){bs=s;best=q}}return best};
const addChildren=q=>{for(const c of NEXT){let x=q+c;if(!grams.has(x)&&!isCovered(x))frontier.add(x)}};
const inferSweep=()=>{let changed=0;for(const q of [...frontier]){let cv=coverOf(q);if(cv){frontier.delete(q);S.covered++;log(q+' • COVERED BY '+cv+' • zero request','gray');changed++;continue}if(tags.has(q)&&knownContainAtLeast(q,K)){frontier.delete(q);addGram(q,K,'inferred-saturated',0);S.inferred++;S.processed++;pending++;addChildren(q);log(q+' • INFERRED SATURATED (≥40 known) • descendants retained','orange');changed++;if(changed>=300)break}}return changed};
const processResult=(q,r)=>{let before=tags.size;for(const x of r.tags)addTag(x.name,x.count);let fresh=tags.size-before,count=r.raw,kind=count<K?'closed':'saturated';frontier.delete(q);addGram(q,count,kind,fresh);S.processed++;pending++;S.yieldEwma=S.processed===1?fresh:S.yieldEwma*.82+fresh*.18;if(count<K){let n=pruneFrontier();log(q+' • CLOSED ('+count+'/40) • +'+fresh+' tags • pruned '+n,'green')}else{addChildren(q);log(q+' • SATURATED (40/40) • +'+fresh+' tags • descendants retained','blue')}return fresh};
const log=(t,kind='gray')=>{hist.unshift({t,kind});hist=hist.slice(0,8);if(lg){lg.innerHTML=hist.map(x=>'<div style="padding:4px 6px;margin-top:4px;border-radius:7px;background:'+(x.kind==='red'?'rgba(255,69,58,.28)':x.kind==='green'?'rgba(52,199,89,.20)':x.kind==='orange'?'rgba(255,159,10,.20)':x.kind==='blue'?'rgba(10,132,255,.20)':'rgba(127,127,127,.16)')+'">'+esc(x.t)+'</div>').join('')}},esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const wakeStatus=()=>{if(!wk)return;if(!('wakeLock'in navigator))wk.textContent='screen: wake lock unsupported';else if(wake&&!wake.released)wk.textContent='screen: awake';else wk.textContent='screen: normal'},wakeOn=async()=>{if(!('wakeLock'in navigator)){wakeStatus();return}if(wake&&!wake.released){wakeStatus();return}try{wake=await navigator.wakeLock.request('screen');wake.addEventListener('release',wakeStatus);wakeStatus()}catch{wake=null;wakeStatus()}},wakeOff=async()=>{try{if(wake&&!wake.released)await wake.release()}catch{}wake=null;wakeStatus()};
const refresh=(q,mode)=>{pruneFrontier();let [mn,mx]=depthRange(),eff=S.requests?(tags.size-S.importedTags)/S.requests:0,elapsed=session?(performance.now()-session.t0):0,tpm=elapsed>1000?(tags.size-session.tags0)*60000/elapsed:0,rpm=elapsed>1000?(S.requests-session.req0)*60000/elapsed:0;if(ct)ct.textContent=tags.size.toLocaleString()+' tags • '+S.requests.toLocaleString()+' v8 requests • '+eff.toFixed(2)+' net tags/request • '+S.inferred.toLocaleString()+' free inferences';if(px)px.textContent='scheduler '+(mode||'—')+' • frontier '+frontier.size.toLocaleString()+' • depth '+(mn||'—')+(mx&&mx!==mn?'–'+mx:'')+' • yield EWMA '+S.yieldEwma.toFixed(2)+' • '+(S.latEwma?Math.round(S.latEwma)+' ms/request':'latency —')+' • '+(session?tpm.toFixed(0)+' tags/min • '+rpm.toFixed(0)+' req/min':'session idle')+' • current '+(q||'—');wakeStatus()};
const start=async()=>{if(running||S.done)return;running=1;paused=0;session={t0:performance.now(),tags0:tags.size,req0:S.requests};await wakeOn();try{st.textContent=S.ep?'running • adaptive language scheduler':'learning autocomplete endpoint…';while(!paused&&!S.done){let spins=0;while(inferSweep()&&spins++<20){}if(pending>=BATCH)await flush();pruneFrontier();if(!frontier.size){S.done=1;break}let mode=chooseMode(),q=choose(mode);if(!q){S.done=1;break}let cv=coverOf(q);if(cv){log('⚠️ invariant prevented request: '+q+' contains CLOSED '+cv,'red');frontier.delete(q);S.covered++;continue}refresh(q,mode);let r=S.ep?await direct(q):await discover(q);processResult(q,r);S.turn++;st.textContent='running • '+mode+' mode • direct JSON';refresh(q,mode);if(pending>=BATCH)await flush()}if(S.done){await flush();st.textContent='finished • all required candidates resolved';log('FINISHED • completeness frontier is empty','green')}else if(paused)st.textContent='paused • saved'}catch(e){console.error(e);try{await flush()}catch{}st.textContent='stopped: '+String(e.message||e);log('STOPPED • '+String(e.message||e),'red')}finally{running=0;session=null;await wakeOff();refresh()}};
const pause=async()=>{paused=1;st.textContent='saving…';try{await flush();await wakeOff();st.textContent='paused • saved'}catch{st.textContent='pause save error'}},copyTags=async()=>{let t=[...tags.keys()].sort().join('\n');try{await navigator.clipboard.writeText(t)}catch{let a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.left='-9999px';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}st.textContent='copied '+tags.size.toLocaleString()+' tags'},exp=()=>{let arr=[...tags].sort(([a],[b])=>a.localeCompare(b)).map(([name,count])=>({name,count})),a=document.createElement('a'),b=new Blob([JSON.stringify({version:8,count:arr.length,requests:S.requests,processed:S.processed,inferred:S.inferred,covered:S.covered,importedTags:S.importedTags,importedProofs:S.importedProofs,yieldEwma:S.yieldEwma,tags:arr},null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download='tags-v8.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},reset=async()=>{if(!confirm('Erase all Tag Gremlin v8 progress? v7 storage will stay untouched and can be imported again after reload.'))return;paused=1;await wakeOff();try{db&&db.close()}catch{}let r=indexedDB.deleteDatabase(DBN);r.onsuccess=r.onerror=r.onblocked=()=>location.reload()};
const boot=async()=>{P=document.createElement('div');P.innerHTML='<div style="display:flex;gap:8px;align-items:center"><b style="font-size:17px">Tag Gremlin v8</b><button id="tgx" style="margin-left:auto">×</button></div><div id="tgs" style="margin-top:8px;font-weight:700">loading v8…</div><div id="tgw" style="font-size:12px;margin-top:3px;opacity:.8">screen: normal</div><div id="tgc" style="font-size:13px;margin-top:7px">—</div><div id="tgp" style="font-size:11px;margin-top:4px;opacity:.82;line-height:1.4">—</div><div id="tgl" style="font-size:11px;margin-top:7px;max-height:145px;overflow:auto"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px"><button id="tgr">Start / Resume</button><button id="tga">Pause + Save</button><button id="tgb">Copy tags</button><button id="tge">Export JSON</button><button id="tgd" style="grid-column:1/-1">Reset v8</button></div>';Object.assign(P.style,{position:'fixed',zIndex:2147483647,left:'12px',right:'12px',top:'12px',background:'rgba(28,28,30,.97)',color:'#fff',padding:'14px',borderRadius:'16px',boxShadow:'0 10px 35px rgba(0,0,0,.35)',fontFamily:'-apple-system,BlinkMacSystemFont,Arial,sans-serif'});for(const b of P.querySelectorAll('button'))Object.assign(b.style,{minHeight:'40px',border:0,borderRadius:'10px',fontWeight:700});document.documentElement.appendChild(P);st=P.querySelector('#tgs');wk=P.querySelector('#tgw');ct=P.querySelector('#tgc');px=P.querySelector('#tgp');lg=P.querySelector('#tgl');P.querySelector('#tgr').onclick=start;P.querySelector('#tga').onclick=pause;P.querySelector('#tgb').onclick=copyTags;P.querySelector('#tge').onclick=exp;P.querySelector('#tgd').onclick=reset;P.querySelector('#tgx').onclick=()=>P.style.display='none';try{await load();st.textContent=S.done?'finished • saved':S.importedTags?'ready • imported '+S.importedTags.toLocaleString()+' v7 tags + '+S.importedProofs.toLocaleString()+' proofs':'ready • fresh v8';log('v8 scheduler ready • language prior affects order only; CLOSED proofs control pruning','gray');refresh()}catch(e){st.textContent='storage error: '+e.message}};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&running&&!paused)wakeOn();else wakeStatus()});window.__tagGremlinV8={show:()=>P&&(P.style.display='block'),start,pause};boot()
})()