<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>JotunnCompat.FastPath</AssemblyName>
    <RootNamespace>JotunnCompat.FastPath</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>..\..\lib\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
